language: node_js

node_js:
  - 8
  - 6
  - 12

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: build
      node_js: lts/*
      provider: script
      skip_cleanup: true
      script:
        - npx semantic-release
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release