language: node_js

node_js:
  - 10
  - 8
  - 6

branches:
  only:
    - master

# Retry install on fail to avoid failing a build on network/disk/external errors
install:
  - travis_retry npm install

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release